AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  prediction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: prediction/lambda_function.lambda_handler
      Runtime: python2.7
      Description: ''
      MemorySize: 1024
      Timeout: 15
      Role:
        'Fn::Sub': 'arn:aws:iam::${AWS::AccountId}:role/MLDeploymentRole'

